### ISSUE TITLE
OSX Icon ignore

### ISSUE THREAD

**Issue by jwmann** [joeblau/gitignore.io#167]
Hey there,

I recently replaced one of my old gitignore's with a generated one using the osx parameter.
The OSX gitignore includes the Icon file specifically like `Icon^M^M` however, this format doesn't always seem to be the case.

Some of my Icon files were showing up as `Icon^M` and thus were accidentally included in the repo and actually broke our deployment solution (I guess it couldn't parse the character properly). I think maybe Google Drive stripped its last bit from the filename and it was somehow copied in.

I'm wondering if it would be beneficial to make this Icon ignore to be able to match a bit more.
This comment here makes a pretty good case for it. http://stackoverflow.com/a/33974028

I'm not 100% sure exactly the best way to approach that. I would like to discuss whether a wider match would be a good idea to be added to gitignore.io and how much the new ignore would match.

**Comment by joeblau** [comment]
There are two parts to this.

1. The OSX .gitignore template is actually maintained by GitHub @ https://github.com/github/gitignore/blob/master/Global/OSX.gitignore.  My reference to their template is simply a git submodule that pulls in their file list.  In order to get this issue addressed at the root level, I would advise filling and issue on GitHub's official repo.

2. We *can* fix this now.  I've created a .patch format in the [/data/patch](https://github.com/joeblau/gitignore.io/tree/master/data/patch) directory which appends any changes to the original template.  We could create an `OSX.patch` file to address the issue.  I'm not sure exactly what should go in the .patch file, but if you either submit a pull request or let me know, I'll add it.

Thanks for finding this.

**Comment by jwmann** [comment]
After some tinkering, I don't think there's a simple way to accomplish this that's not a semi-wildcard like a `^M+`
Doing something like `Icon*` would be irresponsible for something that would spread across many projects and systems.

The only way to achieve regex like filename matching is by importing `fnmatch` first but that's not an ideal solution either.

I think in this case, dealing with the edge-case of improperly formatted Icon files manually would be a better option.

**Comment by joeblau** [comment]
:*(

**Comment by Leif-W** [comment]
On [Microsoft/vscode#127](https://github.com/Microsoft/vscode/issues/127), this issue is mentioned several times with many suggestions for `Icon?`.  @jwmann does `Icon?` work for you?  I don't have OSX for testing.
