### ISSUE TITLE
Add .orig files to ignore list

### ISSUE THREAD

**Issue by ismusidhu** [joeblau/gitignore.io#209]
Please add .orig files to ignore list. This is a common problem that after merging (when there are conflicts to be resolved), .orig files gets added to source control.

**Comment by joeblau** [comment]
For what type of project?

**Comment by ismusidhu** [comment]
I use visual studio. But the problem is common i.e. from git command line.
I'm using Windows system.

**Comment by joeblau** [comment]
Ah yes you are correct!  I"ll need to look into the `.orig` files because I'm not 100% sure what happens if you'd don't clean those files up and just ignore them.  Do subsequent merges throw errors if they the `.orig` files are still lurking around.

You also may h ave just discovered a new class of template that should be applied globally to all files at least once.
