### ISSUE TITLE
support CLion IDE

### ISSUE THREAD

**Issue by brendon-** [joeblau/gitignore.io#263]
Somewhat different than intellij, also changing with each revision of the application so this would be a nice place to update once for everyone.  may extend intellij and only add the clion specific items that are not already included in intellij.

**Comment by joeblau** [comment]
You have a few options in this respect.  If you want to extend intellij, you can make a symlink from:

`/data/custom/CLion.template` → `/data/gitignore//Global/JetBrains.gitignore`

Then add a patch (which I should really name to extension since that what it does) and add the extended functionality in

`/data/patch/CLion.patch`

**Comment by joeblau** [comment]
@brendon If you  know of any CLion specific items, please let me know.  I'm going to symlink this JetBrains.

**Comment by brendon** [comment]
Wrong @brendon. Try @brendon-.

**Comment by joeblau** [comment]
Sorry!

@brendon- ??

**Comment by brendon-** [comment]
Nothing specific any longer actually, I no longer have a current license,
sorry this kind of fell off my radar.

On Jan 29, 2017 6:12 AM, "Joe Blau" <notifications@github.com> wrote:

Sorry!

@brendon- <https://github.com/brendon-> ??

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joeblau/gitignore.io/issues/263#issuecomment-275907334>,
or mute the thread
