### ISSUE TITLE
line endings style is not unified

### ISSUE THREAD

**Issue by gzm55** [joeblau/gitignore.io#266]
Hi,

On linux, the result of 

https://www.gitignore.io/api/c,macos,java

is mix two styles of line endings, the mac os part is \r\n, and other lines are \n.

I know \r is the mac style, but the mixing style is not a good practice. can we output \n everywhere, or give a http param to decide the ending?

**Comment by joeblau** [comment]
Can you send me an output of where you're seeing the `\r\n`?

**Comment by joeblau** [comment]
N/M I see them.

![screen shot 2016-12-18 at 9 25 12 am](https://cloud.githubusercontent.com/assets/1218847/21294817/e976194e-c503-11e6-9d9f-01e8482dbd4a.png)

The best thing to do is file a bug on: https://github.com/github/gitignore because I simply include this repo as a submodule.  [Here is the link to the original template](https://github.com/github/gitignore/blob/master/Global/macOS.gitignore) and it looks like the `\r` that is in there is just a part of the comment.
