### ISSUE TITLE
Export in other VCS formats

### ISSUE THREAD

**Issue by wwarlock** [joeblau/gitignore.io#286]
Right now `gitignore.io` supports only git format.
It would be great if it will also supports other VCSes (like Mercurial for example).
I'm not very active Mercurial (or any other vcs) user but I've required that functionality sometimes.
I don't think that is very hard task to refactor your generator.
And that modification will be very helpful.

**Comment by joeblau** [comment]
The only other VCS I've personally used is CVS and that was about 8 years ago.  Since I don't personally use anything outside of git, I would be a very poor [high-judgement champion](http://www.recode.net/2016/5/31/11826584/amazon-new-ideas-projects).  If you or someone else wants be that for other VCSes — I'm all for it.  The site name is going to be a little off for the others though :-D.

**Comment by joeblau** [comment]
I just stood up: https://www.hgignore.com.  

I right now, it's just a clone of this site, but with my mercurial theme  color (blue).  I still need to figure out if i can translate git templates to mercurial or if I need an entirely new template database.  I'm going to close this task out and add todo tasks on the [hgignore repository](https://github.com/dvcs/hgignore.com)

**Comment by wwarlock** [comment]
Thanks a lot!
