### ISSUE TITLE
Search doesn't work in Safari (10.0.3)

### ISSUE THREAD

**Issue by katzenbaer** [joeblau/gitignore.io#295]
Searching for any term, e.g. "Python" and "Xcode", doesn't work on Safari. There were no Javascript errors output to console. I was not able to reproduce the issue on Chrome (56.0.2924.87)

**Comment by katzenbaer** [comment]
Just kidding, it's happening on Chrome now too. I wonder if it's because I used the browser to navigate back from a generated .gitignore file? Restarting the page and restarting Chrome does not resolve the issue. Will try clearing cache next..

**Comment by katzenbaer** [comment]
Nope, clearing Browser History, Download History, Cookies and other site and plugin data, Cached images and files, and Hosted app data did not resolve the issue.

**Comment by joeblau** [comment]
When you're saying "doesn't work" are you going to https://www.gitignore.io and searching?

**Comment by katzenbaer** [comment]
Yup.. but it's working now on my phone. Maybe it was a network issue.

**Comment by joeblau** [comment]
Safari is my primary browser so that's what I used when developing the site.  Every time I test, I'm on Safari latest and just tested the site on Chrome 56.0.2924.87 and they both work.


1. Does this endpoint work for you?

https://www.gitignore.io/dropdown/templates.json?term=py&_type=query&q=a

All the search box does is make a `GET` request to that end point multiple times with whatever is populated in the `term` parameter and return that back to the Select2 dropdown.

2. Does the staging server work?

There also could be a potential caching issue with Heroku's dynos.  Can you check and see if the stating server works?

https://gitignoreio-stage-swift.herokuapp.com

3. Are you trying to run locally?

The only time I've seen problems like that are when people are trying to run the site locally because they don't follow the git clone **--recursive** instructions.  They never download the submodule for GitHub's main repo and therefore are missing a lot of templates.

4. Where are you located?

Maybe I can try and VPN into whatever country (if you're not in the US) you're located and see if there is a DNS issue.

5. What is your on your desktop DNS? 

Mines is `8.8.8.8`

**Comment by XDRosenheim** [comment]
I think the issue here is that the "search bar" doesn't like capitalized letters.  

Examples:

- Writing "Windows" gives no results, whilst "windows" does.
- Writing "Java" gives no results, whilst "java" does.
- Two results: https://www.gitignore.io/dropdown/templates.json?term=py
- No results: https://www.gitignore.io/dropdown/templates.json?term=Py

[![https://gyazo.com/1db9f9f4a32335b9208108cfbb71ad7f](https://i.gyazo.com/1db9f9f4a32335b9208108cfbb71ad7f.gif)](https://gyazo.com/1db9f9f4a32335b9208108cfbb71ad7f)

_Chrome Version 56.0.2924.87 if that is any help._

**Comment by joeblau** [comment]
@XDRosenheim Thanks for figuring out the problem!

@katzenbaer `master` is building right now — Once it passes CI I'll push it to production.
