### ISSUE TITLE
missing comma (,) at line endings in api/list

### ISSUE THREAD

**Issue by baykant** [joeblau/gitignore.io#299]
request to https://www.gitignore.io/api/list returns recognized types but missing comma on line endings. 

example:
`momentics,monodevelop,nanoc,ncrunch,nesc`  
`netbeans,nette,nim,ninja,node`

which in return, parsing the type list results "nescnetbeans"

**Comment by joeblau** [comment]
The reason for this is formatting stems from #156  when you use `gi list | column -ts ","` it will format all of the results in clean columns.

<img width="721" alt="screen shot 2017-02-11 at 7 13 46 pm" src="https://cloud.githubusercontent.com/assets/1218847/22858532/7f175692-f08e-11e6-9acb-9b212e9aaab1.png">

What exactly are you trying to do, because there are two other formats for getting the list of files introduced in #160:
- `https://www.gitignore.io/api/list?format=lines`
- `https://www.gitignore.io/api/list?format=json`

**Comment by baykant** [comment]
Thanks for info. I use gitignore plugin for netbeans https://github.com/junichi11/netbeans-gitignore-io-plugin and before change it was parsing the list using comma. I will open an issue on that project and close this one.

**Comment by joeblau** [comment]
👍
