### ISSUE TITLE
Laravel ignore paths update

### ISSUE THREAD

**Issue by OliverZiegler** [joeblau/gitignore.io#331]
As stated in #122 vendor and node_modules folder are added in gitignore but not like suggested.

When using the current gitignore for laravel, vendor is inserted like `vendor/`  but when you use `php artisan vendor:publish` command you get vendor folders eg. in views or public folder where you intend to edit files and commit in git.
So I think and would suggests just to ignore the composer vendor folder like `/vendor`.

Please correct me if I overlooked something :)

**Comment by joeblau** [comment]
Thanks for the comment.  Since that template was submitted, it's since been merged into [GitHub's template repository](https://github.com/github/gitignore).  I include github/gitignore as a submodule so I can't remove template lines, I can only append them (via `.patch`).  If you think that there needs to be a change to Laravel that removes lines, you'll need to file it at: https://github.com/github/gitignore — And they only take pull requests :).
