### ISSUE TITLE
.project, .classpath currently not ignored

### ISSUE THREAD

**Issue by gaellalire** [joeblau/gitignore.io#345]
This commit seems to be the cause

https://github.com/dvcs/gitignore/commit/9a2b4b08832124dcd9d52b81e81cf1cf090a8160#diff-033fe2949017fb8e2dffb216a2bafeb7

It is intentional ?

**Comment by joeblau** [comment]
Yes, this file is copied from which is the current source for most of the templates: https://github.com/github/gitignore/blob/master/Global/Eclipse.gitignore

If those should be ignore, we can create a `Eclipse.patch` which will append the changes.  If you want, you can submit that to dvcs/gitignore or I can add it later tonight.

```
# Eclipse Core		
.project		

# JDT-specific (Eclipse Java Development Tools)		
.classpath		 
```

**Comment by gaellalire** [comment]
I think you should never remove previously ignored files/directories.
You did it with iml on idea and it has generated problems. You fixed it via intellj+iml, maybe you will fix with eclipse+project but your users may become tired of following your new templates.
If some user wants to keep some IDE specific data just add a minus template like eclipse-project or eclipse+noproject ...

My 2 cents

**Comment by joeblau** [comment]
That makes sense and I totally agree.

The peace that you might be missing is that gitignore.io doesn't control that file. `dvcs/gitignore` [make a copy with a synchronize script](https://github.com/dvcs/gitignore/blob/master/.travis/synchronize.sh) of the `github/gitignore` (including that Eclipse template) everyday so if GitHub changes the file, it changes on `dvcs/gitignore`.  If you look at GitHub's repository, they are the owners of the Eclipse template and they have a documented the reason for removing those files in their patch: https://github.com/github/gitignore/commit/0674ff5b5c77935cbb2ea2269c001bfd84aa1aa5

If you feel strongly about this, you should probably comment there as well.

GitHub is still currently the source of truth for these files so sometimes they make changes that I don't know bout until people comment.  This is why I created the patch system because this isn't the first time GitHub has removed or excluded template features that people rely on.

If you have an idea of how to better manage the syncing, I'm all for it.

**Comment by joeblau** [comment]
This issue was moved to dvcs/gitignore#8
