### ISSUE TITLE
hexo template lack .deploy_git

### ISSUE THREAD

**Issue by kimseongrim** [joeblau/gitignore.io#450]
https://www.gitignore.io/api/hexo

### Expected Behavior:
```
### hexo ###
db.json
public/
.deploy_git
```
### Actual Behavior:
```
### hexo ###
db.json
public/
```

**Comment by djkeh** [comment]
gitignore.io gets template information from dvcs/gitignore, so when you try to get a hexo template you get:

https://github.com/dvcs/gitignore/blob/b952595ab1f6e452dc20f9c7c9ed636134b95f44/templates/Hexo.gitignore

It seems currently not to have `.deploy_git` rule, so technically your actual behavior is the expected behavior.
You could have a look at github/gitignore as well, however, it doesn't even have template for hexo.

Speaking of putting `.deploy_git` into the current template,
I'm not a hexo user so I'm afraid I can't give my personal comment on that.
It'd also be grateful if you give us more detailed explanation including why we need `.deploy_git` to be added to the hexo template.

**Comment by kimseongrim** [comment]
> Speaking of putting `.deploy_git` into the current template,
> I'm not a hexo user so I'm afraid I can't give my personal comment on that.
> It'd also be grateful if you give us more detailed explanation including why we need `.deploy_git` to be added to the hexo template.

#### Deploy after generation finishes. Deploys my website.
```bash
# The .deploy_git directory will be automatically generated.
$ hexo deploy
```

#### hexo official documentation and plugins

- https://hexo.io/docs/commands.html#deploy
- https://github.com/hexojs/hexo-deployer-git

*Because it is a feature of publishing blog, I think used by many hexo users.*

**Comment by joeblau** [comment]
Please submit a [PR to the template for Hexo](https://github.com/dvcs/gitignore/blob/master/templates/Hexo.gitignore) — This repository is not for template updates.
